version: '3'

services:
  db:
  image: postgres:latest
  restart: always
  port: 
    - 5432:5432
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: testdb
  volumes:
    - dbdata:/var/lib/postgres

volumes:
  dbdata: