version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    volumes:
      - dbdata:/var/lib/postgres
  
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - cache:/data

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always
    volumes: 
      - mail/data

volumes:
  dbdata:
    driver: local
  cache:
    driver: local